blog/urls.py
from django.conf.urls import url

from blog.views import HistoryView, News1View,AuthorNewsListView, report_view,IndexView, PostView, CommentView, RepositoryView, RepositoryDetailView, TagListView, \
    CategoryListView, AuthorPostListView, CommentDeleteView,NewsView,emtest_view,change_view, CollectView,CatalogueListView,register_views, \
    ceshi, show_Agreement, show_aboutUs, contact_us, SearchView, RecommendView, TagsView


urlpatterns = [
    url(r'^$', IndexView.as_view()),
    url(r'^news/$',NewsView.as_view()),
    url(r'^post/(?P<pk>[0-9]+)$', PostView.as_view()),
    url(r'^news/(?P<pk>[0-9]+)$', News1View.as_view()),
    url(r'^comment/add/(?P<pk>[0-9]+)$', CommentView.as_view()),
    url(r'^comment/delete/(?P<pk>[0-9]+)$', CommentDeleteView.as_view()),
    url(r'^repository$', RepositoryView.as_view()),
    url(r'^repository/(?P<pk>[0-9]+)$', RepositoryDetailView.as_view()),
    url(r'^tag/(?P<slug>[\w\u4e00-\u9fa5]+)$', TagListView.as_view()),
    url(r'^catalogue/(?P<slug>[0-9]+)$', CatalogueListView.as_view()),
    url(r'^author/(?P<pk>[0-9]+)$', AuthorPostListView.as_view()),
    url(r'^test/$',emtest_view,name='sp'),
    url(r'^change_sc/$',change_view,name='ch'),
    url(r'^blog/report/(?P<pk>[0-9]+)$',report_view.as_view()),
    url(r'^author1/(?P<pk>[0-9]+)$', AuthorNewsListView.as_view()),#新闻归档
    url(r'^category/(?P<pk>[0-9]+)$', CategoryListView.as_view()),
    url(r'^add/collect/(?P<pk>[0-9]+)$',CollectView.as_view()),
# 123456
    url(r'^register/$',register_views),
    # url(r'captcha/$', verifycode),
    url(r'ceshi/$',register_views),
    url(r'tiaozhuan/$',ceshi),
    url(r'agreement/$',show_Agreement),
    url(r'aboutus/$',show_aboutUs),
    url(r'contact/$',contact_us),
    # url(r'^change_sc_done/$',change_view_done,name='chd'),
    #####
    url(r'^recommend/(?P<pk>[0-9]+)$', RecommendView.as_view()),
    url(r'^search/(?P<pk>.+)$', SearchView.as_view(), name='search'),# 新增
    url(r'^history/(?P<pk>[0-9]+)$',HistoryView.as_view()),#查看历史文章
	url(r'^tags/$', TagsView.as_view()),
]

heartoftech/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'', include('blog.admin_urls')),
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
  # -*- coding:utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.db import models
from tagging.models import Tag
from tagging.fields import TagField
from tagging.registry import register

STATUS = {
        0: u'草稿',
        1: u'发布',
        2: u'删除',
}
# NTYPE = {
#      0: u'博文'
# }
EDITOR = [
    u'tinyMCE',
    u'MarkDown',
]


# 复写TagField的sava方法，让它不做任何事
class TagField_Mine(TagField):
    def _save(self, **kwargs):
        pass


# class Editor(models.Model):
#     name = models.CharField(max_length=20, primary_key=True)
#     avaliable = models.BooleanField(default=True)
#
#     def __str__(self):
#         return self.name


class User(AbstractUser):
    name = models.CharField(max_length=12)
    # editor_choice = models.ForeignKey(Editor, null=True, blank=True, default="tinyMCE")
    editor_choice = models.CharField(max_length=20, default='tinyMCE')
    avatar_path = models.ImageField(upload_to="/avatar", default="/static/image/avatar_default.jpg")
    alipay_qrcode_path = models.ImageField(upload_to="/alipay_qrcode", blank=True)
    wechat_qrcode_path = models.ImageField(upload_to="/wechat_qrcode", blank=True)

    def __str__(self):
        return self.name


class Maincategory(models.Model):
    name = models.CharField(max_length=50,unique=True)

    def __str__(self):
        return self.name



class Catalogue(models.Model):
    name = models.CharField(max_length=20)
    catename = models.ForeignKey(Maincategory)

    def __str__(self):
        return self.name

class Secret(models.Model):
     s_user = models.ForeignKey(settings.AUTH_USER_MODEL)
     f_question = models.CharField(max_length=100)
     f_result = models.CharField(max_length=100)
     s_question = models.CharField(max_length=100)
     s_result = models.CharField(max_length=100)
     t_question = models.CharField(max_length=100)
     t_result = models.CharField(max_length=100)

     def __str__(self):
         return self.s_user


class Post(models.Model):
    title = models.CharField(max_length=100)
    publish_time = models.DateTimeField(auto_now_add=True)  # 第一次保存时自动添加时间
    modify_time = models.DateTimeField(auto_now_add=True)  # 每次保存自动更新时间
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    content = models.TextField()
    catalogue = models.ForeignKey(Catalogue)
    tag = TagField_Mine()
    view_count = models.IntegerField(editable=False, default=0)
    status = models.SmallIntegerField(default=0, choices=STATUS.items())  # 0为草稿，1为发布，2为删除
    stype =models.IntegerField()
    ban = models.IntegerField()
    # ptype = models.SmallIntegerField(default=0, choices=STATUS.items())  # 0为博文，1为新闻，
    # editor_choice = models.ForeignKey(Editor)
    editor_choice = models.CharField(max_length=20)
    recommend_count = models.IntegerField(editable=False, default=0)

    def __str__(self):
        return self.title

    def get_tags(self):
        return Tag.objects.get_for_object(self)

    def update_tags(self, tag_name):
        # 把list转为string
        tag_str = "".join(tag_name)
        Tag.objects.update_tags(self, tag_str)

    def remove_tags(self):
        Tag.objects.update_tags(self, None)

    class Meta:
        ordering = ['-modify_time']

# class News(models.Model):
#       title = models.CharField(max_length=100)
#       publish_time = models.DateTimeField(auto_now_add=True)  # 第一次保存时自动添加时间
#       modify_time = models.DateTimeField(auto_now_add=True)  # 每次保存自动更新时间
#       content = models.TextField()
#       catalogue = models.ForeignKey(Catalogue)
#       status = models.SmallIntegerField(default=0, choices=STATUS.items())  # 0为草稿，1为发布，2为删除
#       author = models.ForeignKey(settings.AUTH_USER_MODEL)
#       view_count = models.IntegerField(editable=False, default=0)
#       editor_choice = models.CharField(max_length=20)
#       def __str__(self):
#         return self.title
#       class Meta:
#         ordering = ['-modify_time']
class Comment(models.Model):
    post = models.ForeignKey(Post)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    publish_Time = models.DateTimeField(auto_now_add=True)
    ip_address = models.GenericIPAddressField()
    content = models.TextField()
    root_id = models.IntegerField(default=0)  # 评论的最上层评论，若该评论处于最上层，则为0，
    parent_id = models.IntegerField(default=0)  # 评论的父评论，若无父评论，则为0

    def __str__(self):
        return self.content


# class NewsComment(models.Model):
#     news = models.ForeignKey(News)
#     author = models.ForeignKey(settings.AUTH_USER_MODEL)
#     publish_Time = models.DateTimeField(auto_now_add=True)
#     ip_address = models.GenericIPAddressField()
#     content = models.TextField()
#     root_id = models.IntegerField(default=0)  # 评论的最上层评论，若该评论处于最上层，则为0，
#     parent_id = models.IntegerField(default=0)  # 评论的父评论，若无父评论，则为0

#     def __str__(self):
#         return self.content
class Carousel(models.Model):
    title = models.CharField(max_length=100)
    img = models.ImageField(upload_to="/carousel")
    post = models.ForeignKey(Post)
    create_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-create_time']


# 知识库模型
class Repository(models.Model):
    title = models.CharField(max_length=100)
    publish_time = models.DateTimeField(auto_now_add=True)  # 第一次保存时自动添加时间
    author = models.CharField(max_length=20)
    content = models.TextField()
    tag = models.ManyToManyField(Tag, blank=True, default="")  # 外键tag可为空，外键被删除时该值设定为默认值“”
    view_count = models.IntegerField(editable=False, default=0)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-publish_time']
class UReport(models.Model):
      ruser = models.ForeignKey(User)
      post = models.CharField(max_length=100)
      report_time = models.DateTimeField(auto_now_add=True)
      reason = models.CharField(max_length=100)
      pname = models.CharField(max_length=50)

      def __str__(self):
          return self.ruser

class Collection(models.Model):
    collect_user = models.ForeignKey(settings.AUTH_USER_MODEL)
    collect_post = models.ForeignKey(Post)

class RecommendList(models.Model):
    referee = models.ForeignKey(settings.AUTH_USER_MODEL)
    recommend_post = models.ForeignKey(Post)

register(Post)

blog/templates/blog/history.html
{% extends "./blog/base.html" %}

{% block title %}
    博客
{% endblock %}

{% block main %}
    <div class="row">
        <div id="container-blog" class="col-md-8 col-lg-9">
            <!-- 左栏内容 -->
            <div>
                <!-- 轮播 -->
                {% if carousel_page_list %}
                    {% include "./blog/include/carousel.html" %}
                {% endif %}

                <!-- 首页文章列表 -->
                {% if objects.object_list %}
				<font size="4" color="blue">博主 {{objects.object_list.0.author.name}} 发表的历史文章：</font>
                    {% for post in objects.object_list %}
                    <p><font size="5">

</font></p>
                        <div class="home-post well clearfix">
                                    <div class="pre-cat">
                                    <!-- <img src=""> -->
                                    <a href="/recommend/{{post.id}}"><img src="/static/image/tiny01.gif">{{ post.recommend_count }}</a>
                                    </div>
                            <div class="post-title underline clearfix">
                                <a href="/catalogue/{{ post.catalogue.id }}">
                                    <div class="pre-cat">
                                        <div class="pre-catinner btn">
                                            {{ post.catalogue.name }}
                                        </div>
                                        <div class="pre-catarrow">
                                        </div>
                                    </div>
                                </a>

                                <h1>
                                    <a href="/post/{{ post.id }}">{{ post.title }}</a>
                                </h1>

                                <div class="post-info">
            <span>
                <span class="glyphicon glyphicon-calendar"></span>
                {{ post.publish_time | date:"Y年m月d日 H:i" }}
            </span>
            <span>
                <span class="glyphicon glyphicon-comment"></span>
                {{ post.comment_set.all | length }}
            </span>
            <span>
                <span class="glyphicon glyphicon-eye-open"></span>
                {{ post.view_count }}
            </span>
            <span>
                <span class="glyphicon glyphicon-user"></span>
               {{ post.author.name }}
            </span>

                                    <div class="post-tags">

                                        {% for tag in post.get_tags %}
                                            <a href="/tag/{{ tag.name }}"
                                               class="{% if forloop.counter0 %}hidden-xs{% endif %} ">
                                                <span class="label label-blog-{{ forloop.counter }} btn">{{ tag.name }}</span>
                                            </a>
                                        {% endfor %}
                                        <a class="visible-xs-inline-block">
                                            <span class="label label-blog-2 btn ">...</span>
                                        </a>
                                    </div>
                                </div>
                            </div>

                            <div class="post-content">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <p>
                                            {% autoescape off %}
                                            {{ post.content|striptags|slice:"200"}}
                                            {% endautoescape %}
                                            {% if post.content|length > 200 %}
                                                ...
                                            {% endif %}
                                        </p>
                                        <a type="button" class="btn btn-blog pull-right hidden-xs"
                                           href="/post/{{ post.id }}">阅读全文</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}

                <!-- 分页 -->
                {% if objects %}
                    {% include "./blog/include/pagination.html" %}
                {% endif %}

            </div>

        </div>

        <div class="marginTop10 col-md-4 col-lg-3 hidden-xs">
            {% include "./blog/include/blog_search.html" %}
            {% include "./blog/include/year_write_posts.html" %}
            {% include "./blog/include/hot_posts.html" %}
            {% include "./blog/include/friendly_link.html" %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends "./blog/base.html" %}

{% block title %}
    博客
{% endblock %}

{% block main %}
    <div class="row">
        <div id="container-blog" class="col-md-8 col-lg-9">
            <!-- 左栏内容 -->
            <div>
                <!-- 轮播 -->
                {% if carousel_page_list %}
                    {% include "./blog/include/carousel.html" %}
                {% endif %}
                
                <!-- 首页文章列表 -->
                {% if objects.object_list %}
                    {% for post in objects.object_list %}
                    
                        <div class="home-post well clearfix">
                                    <div class="pre-cat">
                                    <!-- <img src=""> -->
                                     <img id= "rec" src="/static/image/tiny01.gif" onclick="refresh({{post.id}})" ><span id="span{{post.id}}" class="ok">{{post.recommend_count}}</span>
                                    </div>
                            <div class="post-title underline clearfix">
                                <a href="/catalogue/{{ post.catalogue.id }}">
                                    <div class="pre-cat">
                                        <div class="pre-catinner btn">
                                            {{ post.catalogue.name }}
                                        </div>
                                        <div class="pre-catarrow">
                                        </div>
                                    </div>
                                </a>

                                <h1>
                                    <a href="/post/{{ post.id }}">{{ post.title }}</a>
                                </h1>

                                <div class="post-info">
            <span>
                <span class="glyphicon glyphicon-calendar"></span>
                {{ post.publish_time | date:"Y年m月d日 H:i" }}
            </span>
            <span>
                <span class="glyphicon glyphicon-comment"></span>
                {{ post.comment_set.all | length }}
            </span>
            <span>
                <span class="glyphicon glyphicon-eye-open"></span>
                {{ post.view_count }}
            </span>
            <span>
                <span class="glyphicon glyphicon-user"></span>
                <a href="/history/{{post.author_id}}">{{ post.author.name }}
            </span>

                                    <div class="post-tags">

                                        {% for tag in post.get_tags %}
                                            <a href="/tag/{{ tag.name }}"
                                               class="{% if forloop.counter0 %}hidden-xs{% endif %} ">
                                                <span class="label label-blog-{{ forloop.counter }} btn">{{ tag.name }}</span>
                                            </a>
                                        {% endfor %}
                                        <a class="visible-xs-inline-block">
                                            <span class="label label-blog-2 btn ">...</span>
                                        </a>
                                    </div>
                                </div>
                            </div>

                            <div class="post-content">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <p>
                                            {% autoescape off %}
                                            {{ post.content|striptags|slice:"200"}}
                                            {% endautoescape %}
                                            {% if post.content|length > 200 %}
                                                ...
                                            {% endif %}
                                        </p>
                                        <a type="button" class="btn btn-blog pull-right hidden-xs"
                                           href="/post/{{ post.id }}">阅读全文</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}

                <!-- 分页 -->
                {% if objects %}
                    {% include "./blog/include/pagination.html" %}
                {% endif %}

            </div>

        </div>

        <div class="marginTop10 col-md-4 col-lg-3 hidden-xs">
            {% include "./blog/include/blog_search.html" %}
            {% include "./blog/include/hot_posts.html" %}
            {% include "./blog/include/year_write_posts.html" %}
            {% include "./blog/include/tag_cloud.html" %}
            {% include "./blog/include/friendly_link.html" %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/news_detail.html
{% extends "./blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}

{% ifequal post.editor_choice 'MarkDown' %}
    {% block css %}
        <link href="/static/editor.md/css/editormd.preview.min.css" rel="stylesheet" type="text/css"/>

        <link href="/static/jquery-emojiarea/jquery.emojiarea.css" rel="stylesheet" type="text/css"/>
    {% endblock %}
{% endifequal %}

{% block js %}
    {% ifequal post.editor_choice 'MarkDown' %}
        <script src="/static/editor.md/editormd.min.js" type="text/javascript"></script>
        <script src="/static/editor.md/lib/marked.min.js" type="text/javascript"></script>
        <script src="/static/editor.md/lib/prettify.min.js" type="text/javascript"></script>
        <script src="/static/editor.md/lib/raphael.min.js" type="text/javascript"></script>
        <script src="/static/editor.md/lib/underscore.min.js" type="text/javascript"></script>
        <script src="/static/editor.md/lib/sequence-diagram.min.js" type="text/javascript"></script>
        <script src="/static/editor.md/lib/flowchart.min.js" type="text/javascript"></script>
        <script src="/static/editor.md/lib/jquery.flowchart.min.js" type="text/javascript"></script>
    {% endifequal %}
    <script src="/static/jquery-emojiarea/jquery.emojiarea.js" type="text/javascript"></script>
    <script src="/static/jquery-emojiarea/packs/basic/emojis.js"></script>

    <script src="/static/js/post-detail.js" type="text/javascript"></script>

    <script type="text/javascript">
        $(function () {

            {% ifequal post.editor_choice 'MarkDown' %}
                var markDownEditor = editormd.markdownToHTML("article_content_view", {
                    htmlDecode: "style, script, iframe",
                    emoji: true,
                    taskList: true,
                    flowChart: true,
                    sequenceDiagram: true,
                });
            {% endifequal %}

            $('#comment_content').emojiarea({
                wysiwyg: false,
                button: '.emoji-button',
            });

        })
        function Collect() {
            if(document.getElementById("collect_label").innerHTML=="收藏"){
                document.getElementById("collect_label").innerHTML="已收藏";
                document.getElementById("collect_icon").className="glyphicon glyphicon-tags";
            }else{
                document.getElementById("collect_label").innerHTML="收藏";
                document.getElementById("collect_icon").className="glyphicon glyphicon-tag";
            }
            $("#collect_form").submit();
        }
    </script>
    <script type="text/javascript">
    function checkform(form){
    var bln = false;
    for(var i = 0; i < form.s.length; i++){
        if(form.s[i].checked) { bln = true; break; }
    }

    if(!bln) { alert("请至少选择一条理由."); return false;}
    else{
        alert("举报成功."); return true;
    }
    }

</script>

{% endblock %}

{% block main %}

    <div class="row">
        <div id="container-blog" class="col-md-8 col-lg-9">
            <!-- 左栏内容 -->
            <div class="well" id="post">
                <div>
                    <h3>{{ post.title }}</h3>
                </div>
                <div>
                    {% for tag in post.get_tags %}
                        <a href="/tags/{{ tag.name }}">
                            <span class="label label-blog-{{ forloop.counter }} btn">{{ tag.name }}</span>
                        </a>
                    {% endfor %}
                </div>
                <div class="post-info">
                <span>
                    <span class="glyphicon glyphicon-calendar"></span>
                    {{ post.publish_time|date:"Y-m-d" }}
                </span>
                <span>
                    <span class="glyphicon glyphicon-comment"></span>
                    {{ post.comment_set.all | length }}
                </span>
                <span>
                    <span class="glyphicon glyphicon-eye-open"></span>
                    {{ post.view_count }}
                </span>
                <span>
                    <span class="glyphicon glyphicon-user"></span>
                    {{ post.author.name }}
                </span>
                </span>
                </div>
                <hr>
                <div class="wrap" id="article_content_view" style="background-color: transparent">
                    {% ifequal post.editor_choice 'tinyMCE' %}
                        {% autoescape off %}
                            {{ post.content }}
                        {% endautoescape %}
                    {% endifequal %}

                    {% ifequal post.editor_choice 'MarkDown' %}
                        <textarea name="content" style="display:none;">
{{ post.content }}
                         </textarea>
                    {% endifequal %}
                </div>
            </div>

            <div class="well blog-comment">
                <div class="blog-comment-edit clearfix">
                  <form action="/blog/report/{{ post.id }}" method="post">
                   {% csrf_token %}
                   <div class="comment-text">
                 <p><input type="checkbox" name="s" value="色情非法" /> 色情非法
                    <input type="checkbox" name="s" value="反动言论" /> 反动言论
                    <input type="checkbox" name="s" value="政治敏感" /> 政治敏感
                    <input type="checkbox" name="s" value="恶意辱骂" /> 恶意辱骂 
                    <input type="checkbox" name="s" value="散播谣言" /> 散播谣言 
                    <input type="checkbox" name="s" value="广告" /> 广告
                 </p>
                 <p><input type="checkbox" name="s" value=" 病毒木马" /> 病毒木马</p>
     
                  <div style="width: 100%"> <input type="submit" class="btn btn-info" value="举报新闻"  onclick="return checkform(this.form);" > </div>
                  </div>
                  </form>
                  <br><br>
                
                    <form action="/comment/add/{{ post.id }}" id="blog-comment-form" method="post" role="form">
                        {% csrf_token %}
                        <div class="comment-text">
                            <textarea maxlength="200" placeholder="写下你的评论，限200字!" name="comment" id="comment_content"></textarea>
                    
                      
                            <div>
                                <input type="submit" name="commit" value="发 表" class="btn btn-info" data-disable-with="提交中...">
                                <div class="emoji-div"><a href="javascript:void(0)" class="emoji-button"><img class="emoji" width="20" height="20" src="/static/jquery-emojiarea/packs/basic/emojis/blush.png"></a></div>
                                <span class="warning" style="display: none"><i class="glyphicon glyphicon-info-sign"></i><span class="warning-text"></span></span>
                            </div>
                        </div>
                    </form>
                </div>
                <ul>
                    {% for root_comment, child_comment_list in comment_list.items %}
                        <li id="comment-{{ root_comment.id }}">
                            <div class="blog-comment-content">
                                <div class="root-comment">
                                    <div class="avatar_top">
                                        <div class="avatar"><img src="{{ root_comment.author.avatar_path }}"></div>
                                        <h4 style="color: #428bca;margin-bottom: 0px">{{ root_comment.author.name }}</h4>
                                        <p style="font-size: 10px;margin-top: 2px">{{ root_comment.publish_Time | date:"Y年m月d日 H:i" }}</p>
                                    </div>
                                    <p style="color: #232323;font-size: 14px">{% autoescape off %}{{ root_comment.content }}{% endautoescape %}</p>

                                    <div class="comment-footer clearfix text-right">
                                        {% ifequal root_comment.author.id user.id  %}
                                            <a class="delete" data-id="{{ root_comment.id }}" href="javascript:void(0)">删除</a>
                                        {% endifequal %}
                                        <a class="reply" data-id="{{ root_comment.id }}"
                                           data-nickname="{{ root_comment.author.name }}"
                                           href="javascript:void(0)">回复</a>
                                    </div>
                                </div>
                                {% if child_comment_list %}
                                <div class="child-comment-list">
                                    {% for child_comment in child_comment_list  %}
                                    <div class="child-comment" id="comment-{{ child_comment.id }}">
                                        <p>
                                            <a class="blue-link" href="#">{{ child_comment.author.name }}</a>：{% autoescape off %}{{ child_comment.content }}{% endautoescape %}
                                        </p>

                                        <div class="child-comment-footer text-right clearfix">
                                            {% ifequal child_comment.author.id user.id  %}
                                                <a data-id="{{ child_comment.id }}" class="delete" href="javascript:void(0)">删除</a>
                                            {% endifequal %}
                                            <a data-parent-id="{{ child_comment.id }}" data-root-id="{{ root_comment.id }}" data-nickname="{{ child_comment.author.name }}" class="child_reply"
                                               href="javascript:void(0)">回复</a>
                                            <span class="reply-time pull-left">
                                                {{ child_comment.publish_Time | date:"Y年m月d日 H:i" }}
                                            </span>
                                        </div>
                                    </div>
                                    {% endfor %}
                                    <form action="/comment/add/{{ post.id }}" class="child-comment-form" method="post" role="form" style="display: none">
                                        {% csrf_token %}
                                        <input type="hidden" name="root_id" value="">
                                        <input type="hidden" name="parent_id" value="">
                                        <div class="child-comment-text">
                                            <textarea maxlength="200" placeholder="写下你的评论，限200字!" name="comment"></textarea>
                                            <div>
                                                <input type="submit" name="commit" value="发 表" class="btn btn-info" data-disable-with="提交中...">
                                                <span class="warning" style="display: none"><i class="glyphicon glyphicon-info-sign"></i><span class="warning-text"></span></span>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                {% else %}
                                    <div class="child-comment-list hide">
                                        <form action="/comment/add/{{ post.id }}" class="child-comment-form" method="post" role="form" style="display: none">
                                        {% csrf_token %}
                                            <input type="hidden" name="root_id" value="">
                                            <input type="hidden" name="parent_id" value="">
                                            <div class="child-comment-text">
                                                <textarea maxlength="200" placeholder="写下你的评论，限200字!" name="comment"></textarea>
                                                <div>
                                                    <input type="submit" name="commit" value="发 表" class="btn btn-info" data-disable-with="提交中...">
                                                    <span class="warning" style="display: none"><i class="glyphicon glyphicon-info-sign"></i><span class="warning-text"></span></span>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                {% endif %}
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            
        </div>

        <div class="marginTop10 col-md-4 col-lg-3 hidden-xs">
            {% include "./blog/include/year_write_posts.html" %}
            {% include "./blog/include/hot_posts.html" %}
            {% include "./blog/include/friendly_link.html" %}
            {% include "./blog/include/blog_search.html" %}
        </div>
    </div>

{% endblock %}